export const SET_TOKEN = 'SET_TOKEN';
export const SET_STATION_ID = 'SET_STATION_ID';
export const SET_STATION_NAME = 'SET_STATION_NAME';
export const GET_CLIMATE_RECORDS = 'GET_CLIMATE_RECORDS';
export const CHANGE_RECORDS = 'CHANGE_RECORDS';
export const EDIT_RECORD = 'EDIT_RECORD';
export const SAVE_RECORD = 'SAVE_RECORDS';
export const GET_PHENOMENA = 'GET_PHENOMENA';